language: objective-c
before_install:
- travis_retry brew install neko --HEAD
- wget -c https://github.com/HaxeFoundation/haxe/releases/download/3.4.2/haxe-3.4.2-osx.tar.gz
- sudo mkdir /usr/local/lib/haxe
- sudo tar xvzf haxe-3.4.2-osx.tar.gz -C /usr/local/lib/haxe --strip-components=1
- sudo ln -s /usr/local/lib/haxe/haxe /usr/local/bin/haxe
- sudo ln -s /usr/local/lib/haxe/haxelib /usr/local/bin/haxelib
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- haxelib dev nme $(pwd)
- git clone https://github.com/HaxeFoundation/hxcpp ~/hxcpp --depth 1
- haxelib dev hxcpp ~/hxcpp
- cd ~/hxcpp/tools/hxcpp
- haxe compile.hxml
- cd ~/hxcpp/tools/run
- haxe compile.hxml
- cd ~/hxcpp/project
- neko build.n
- haxelib -notimeout install nme-toolkit
- haxelib -notimeout install format
- haxelib -notimeout install gm2d
script:
- cd $TRAVIS_BUILD_DIR/tools/nme
- haxe compile.hxml
- cd $TRAVIS_BUILD_DIR/project
- neko build.n
- cd $TRAVIS_BUILD_DIR/tools/nme
- haxelib run nme setup
- haxe test.hxml
- neko bin/TestMain.n
- cd $TRAVIS_BUILD_DIR/tests
- haxe -x RunAll
- cd $TRAVIS_BUILD_DIR/tests/haxe
- haxe compile.hxml
- bin/TestMain
